/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package campinggas;

import Controlador.GerenteControlador_Anterior;
import campinggas.HubAdmin_View;
import java.awt.event.ActionListener;

/**
 *
 * @author alumno
 */
public class ActividadesAdmin extends javax.swing.JFrame {
    
    GerenteControlador_Anterior gerente = new GerenteControlador_Anterior();
    /**
     * Creates new form ActividadesAdmin
     */
    public ActividadesAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        crearActividad = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        visualizarActividades = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("ACTIVIDADES");

        crearActividad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        crearActividad.setText("CREAR");
        crearActividad.setActionCommand("crearActividad1");
        crearActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActividadActionPerformed(evt);
            }
        });

        volver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        visualizarActividades.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        visualizarActividades.setText("VISUALIZAR");
        visualizarActividades.setActionCommand("visualizarActividad");
        visualizarActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarActividadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(visualizarActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(246, 246, 246)
                            .addComponent(crearActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(crearActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(visualizarActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed

        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void crearActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActividadActionPerformed
        CrearActividadAdmin nuevaActividad = new CrearActividadAdmin();
        nuevaActividad.setVisible(true);
    }//GEN-LAST:event_crearActividadActionPerformed

    private void visualizarActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarActividadesActionPerformed
        VisualizarActividadesAdmin visualizarActividades = new VisualizarActividadesAdmin(gerente);
        visualizarActividades.setVisible(true);
    }//GEN-LAST:event_visualizarActividadesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearActividad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton visualizarActividades;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    void setMiActionListener(ActionListener aL) {
        crearActividad.addActionListener(aL);
        visualizarActividades.addActionListener(aL);    
        volver.addActionListener(aL);
    }
}
