/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package campinggas;

import Controlador.GerenteControlador_Anterior;
import Modelo.Modelo;
import Modelo.Parcelas;
import java.awt.event.ActionListener;

/**
 *
 * @author alumno
 */
public class HubAdmin_View extends javax.swing.JFrame {

    AlquilerAdminView alquilerAdmin;
    HistorialAdminView historial;
    PagoAdmin pago;
    ActividadesAdmin act;
    /**
     * Creates new form Gerente
     */
    public HubAdmin_View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAlquilar = new javax.swing.JButton();
        botonGestionarAct = new javax.swing.JButton();
        botonPago = new javax.swing.JButton();
        botonHistorial = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonAlquilar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonAlquilar.setText("Alquilar");
        botonAlquilar.setActionCommand("botonAlquilar");
        botonAlquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAlquilarActionPerformed(evt);
            }
        });

        botonGestionarAct.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonGestionarAct.setText("Gestionar Actividades");
        botonGestionarAct.setActionCommand("gestActividadesButton");
        botonGestionarAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionarActActionPerformed(evt);
            }
        });

        botonPago.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonPago.setText("Pago");
        botonPago.setActionCommand("botonPago");
        botonPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPagoActionPerformed(evt);
            }
        });

        botonHistorial.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonHistorial.setText("Historial");
        botonHistorial.setActionCommand("botonHistorial");
        botonHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHistorialActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Volver");
        jButton5.setActionCommand("volver");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonHistorial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAlquilar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(botonPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonGestionarAct, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)))
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(362, 362, 362))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(botonHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonAlquilar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonPago, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonGestionarAct, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        VentanaPrincipalView login = new VentanaPrincipalView();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void botonAlquilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAlquilarActionPerformed
        
        alquilerAdmin = new AlquilerAdminView();
        alquilerAdmin.setVisible(true);
    }//GEN-LAST:event_botonAlquilarActionPerformed

    private void botonHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHistorialActionPerformed
        //Aquí no se como hacer que haga cosas en el modelo con el MVC
        //EL MODELO SOLO LO PUEDE MODIFICAR EL CONTROLADOR. En teoria.
        //historial = new HistorialAdminView(modelo);
        historial = new HistorialAdminView();
        historial.setVisible(true);
    }//GEN-LAST:event_botonHistorialActionPerformed

    private void botonPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPagoActionPerformed
        //Aquí no se como hacer que haga cosas en el modelo con el MVC
        //EL MODELO SOLO LO PUEDE MODIFICAR EL CONTROLADOR. En teoria.
        //Añadir un actionListener del controlador aqui??
        //pago =  new PagoAdmin(modelo);
        pago =  new PagoAdmin();
        pago.setVisible(true);
    }//GEN-LAST:event_botonPagoActionPerformed

    private void botonGestionarActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarActActionPerformed
        act = new ActividadesAdmin();
        act.setVisible(true);
    }//GEN-LAST:event_botonGestionarActActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAlquilar;
    private javax.swing.JButton botonGestionarAct;
    private javax.swing.JButton botonHistorial;
    private javax.swing.JButton botonPago;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables

    public void setMiActionListener(ActionListener aL) {
        //ES EL CONTROLADOR EL QUE ABRE LAS VENTANAS, YA QUE ALGUNAS SE TIENEN QUE PASAR CON PARÁMETROS DEL MODELO Y TAL
        //ASÍ QUE SOLAMENTE LE AGREGAMOS EL ACTION LISTENER Y YA
        
        botonAlquilar.addActionListener(aL);
        botonGestionarAct.addActionListener(aL);
        botonHistorial.addActionListener(aL);
        botonPago.addActionListener(aL);
        
    }
}
